### ISSUE TITLE
HTML Markup shows just bellow the Notes Headline when using Plus editor.

### ISSUE THREAD

**Issue by kalivas** [sn-extensions/plus-editor#2]
You can see an example in the image bellow:

![image](https://user-images.githubusercontent.com/7475027/38855627-a9cdeb08-422c-11e8-8bce-a698caf5a39f.png)

**Comment by kalivas** [comment]
PS: I have version 2.1.26 of Standard Notes, and I run on Linux.

**Comment by atmoio** [comment]
This is to be expected..the plus editor converts your note to HTML, and HTML can only be viewed and parsed by the plus editor. The non-extension based parts of the app treat all note text like plain text. On mobile you will also see HTML.

See here: https://standardnotes.org/help/12/why-are-extensions-not-available-on-the-mobile-app
And here: https://standardnotes.org/extensions/plus-editor

**Comment by kalivas** [comment]
Hello, @mobitar thanks for the reply. I understand, do you plan any of the below in the near future?

1. Ability to add a custom subtitle.
2. Ability to hide subtitle so at least it won't look ugly.
3. Ability for the non-extension based parts to ignore HTML tags and fetch only the text on the subtitle?

**Comment by atmoio** [comment]
You can already do #2 by clicking Options in the notes panel, and under Display, hiding Note Preview. For #3, the core application will most likely not have any custom code related to parsing or ignoring HTML. Possibly extensions in the future can do this..

**Comment by kalivas** [comment]
Aa ok, i'll stick with solution 2 for now. Thanks a lot for the help @mobitar..
