### ISSUE TITLE
Support for RTL in the editor

### ISSUE THREAD

**Issue by mmnaseri** [sn-extensions/plus-editor#21]
Hi,

I am on macOS Catalina, 10.15.4, running Standard Notes (extended) 3.4.1. I am using this editor as my default editor in Standard Notes, and I see no support for RTL.

Here is how RTL is treated in the editor today:

<img width="634" alt="Screen Shot 2020-05-24 at 9 49 35 PM" src="https://user-images.githubusercontent.com/543672/82779227-80706d00-9e08-11ea-92fb-7f6407d17a85.png">

If you see https://github.com/standardnotes/desktop/issues/81 you'll find examples of what it should look like. This is an issue for [all RTL languages](https://en.wikipedia.org/wiki/Right-to-left#Current_scripts). The example included is from Arab-160/Aran-161 and specifically uses Persian writing.

Thanks for the great work.

**Comment by JaspalSuri** [comment]
Hi, I'm sorry to hear that RTL isn't working in the latest version of the desktop app.

As you might have noticed, Mo has assigned Ningsong to look into this, but I just wanted to let you know that your feedback has been received. :) @ningsongshen will handle things from here.
