### ISSUE TITLE
[Feature request] Table height and width adjustment

### ISSUE THREAD

**Issue by Random2965** [sn-extensions/plus-editor#3]
In theory I could edit the code, but that is not a convenient way to do it. It would thus be really cool to have some kind of additional menu like in LibreOffice Writer. Having functions like automatic adjustment of tables and manual adjustment option or maybe even have the possibility of clicking and dragging to edit width and height of a table.

**Comment by atmoio** [comment]
The plus editor is based on https://github.com/summernote/summernote/. It's unlikely we'll modify this code ourselves.

**Comment by Random2965** [comment]
Ok, so could it make sense to open an issue at the summernote project?

**Comment by atmoio** [comment]
Yeah I don't see why not. I would try searching to see if there's already an issue for it first.

**Comment by Random2965** [comment]
Sorry, was quite busy lately. Actually a lot of people requested that this is added to summernote.
see:
- https://github.com/summernote/summernote/issues/1577
- https://github.com/summernote/summernote/pull/2835

But it seems that it is already implemented according to this:
- https://github.com/summernote/summernote/issues/1793

Following some comments it seems that a bug with chrome (isn't SN partly based on chrome?) prevents it from properly working:
- https://github.com/summernote/summernote/issues/2394

Since this is not an SN specific issues, I will close this issue and leave the info for others who were wondering if this could be added to SN.

**Comment by atmoio** [comment]
Thanks for the summary! Indeed the desktop app is based on Chromium, so that issue will be present there too.
