### ISSUE TITLE
Copy plain text strips characters

### ISSUE THREAD

**Issue by dreamflasher** [sn-extensions/plus-editor#4]
**Steps** 
- Create an unordered list in plus editor
- Copy this list
- Insert it in a (plain) text editor

**Expected**
All characters are copied, inluding tabs and list characters 

**Actual**
Tabs and list characters are not copied, just the text itself

OS: Windows

**Comment by atmoio** [comment]
The Plus Editor is based on Summernote: https://github.com/summernote/summernote

It's unlikely we'll modify the code ourselves. The best hope of getting this resolved is opening an issue over there.

I'm also exploring other open-source WYSIWYG editors to integrate with SN, so hopefully those will display more consistent behavior.

**Comment by dreamflasher** [comment]
I'll create a ticket there, thank you!
