### ISSUE TITLE
Create paragraph with tab

### ISSUE THREAD

**Issue by dreamflasher** [sn-extensions/plus-editor#5]
Currently pressing tab enters four spaces. Instead it should perform the Paragraph -> Indent action. (And shift tab should Outdent)

**Comment by atmoio** [comment]
Comment from #4:

> The Plus Editor is based on Summernote: https://github.com/summernote/summernote

> It's unlikely we'll modify the code ourselves. The best hope of getting this resolved is opening an issue over there.

>  I'm also exploring other open-source WYSIWYG editors to integrate with SN, so hopefully those will display more consistent behavior.
